[package]
name = "rust-rtree"
version = "0.9.5"
edition = "2021"
authors = ["Xein <1021538027@qq.com>"]
license = "MIT"
description = "A simplified version of the tree tool written in rust."
repository = "https://github.com/xjimlinx/rtree"

[dependencies]
colored = "2.1.0"
