[package]
name = "rtree"
version = "0.9.5"
edition = "2021"
authors = ["xein <1021538027@qq.com>"]
license = "MIT-LICENSE"
description = "A simplified version of the tree tool written in rust."
repository = "https://github.com/xein/rtree"

[dependencies]
colored = "2.1.0"
